package work

import "testing"

func TestFooter(t *testing.T) {
	for _, c := range []struct{ name, body, main, footer string }{
		{"signature", "## Scope\n\nA.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n",
			"## Scope\n\nA.", "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"},
		{"generated by", "## Scope\n\nA.\n\nGenerated by some tool", "## Scope\n\nA.", "Generated by some tool"},
		{"thematic break", "## Scope\n\nA.\n\n---\n\nSent from a phone.", "## Scope\n\nA.", "---\n\nSent from a phone."},
		{"stars", "## Scope\n\nA.\n\n* * *\nB.", "## Scope\n\nA.", "* * *\nB."},
		{"no footer", "## Scope\n\nA.\n\nB.", "## Scope\n\nA.\n\nB.", ""},
		{"setext, not a break", "## Scope\n\nA.\n---\nB.", "## Scope\n\nA.\n---\nB.", ""},
		{"a break above a heading", "Text.\n\n---\n\n## Scope\n\nA.", "Text.\n\n---\n\n## Scope\n\nA.", ""},
		{"signature inside the paragraph", "## Scope\n\nA.\nGenerated with care.", "## Scope\n\nA.\nGenerated with care.", ""},
		{"signature right under the heading", "## Scope\nGenerated by the build.", "## Scope\nGenerated by the build.", ""},
		{"in fenced code", "## Scope\n\n```\n\n---\n```", "## Scope\n\n```\n\n---\n```", ""},
		{"an info string does not close a fence", "## Scope\n\n```md\n```go\n\n---\nB.\n```", "## Scope\n\n```md\n```go\n\n---\nB.\n```", ""},
		{"a longer fence closes", "## Scope\n\n````\n```\n````\n\n---\nB.", "## Scope\n\n````\n```\n````", "---\nB."},
		{"no section", "Some text.\n\n🤖 Generated with X", "Some text.", "🤖 Generated with X"},
	} {
		main, footer := Footer(c.body)
		if main != c.main || footer != c.footer {
			t.Errorf("%s: Footer = %q, %q; want %q, %q", c.name, main, footer, c.main, c.footer)
		}
	}
	if got := Sections("## Scope\n\nA.\n\n🤖 Generated with X\n")["Scope"]; got != "\nA.\n" {
		t.Errorf("Scope = %q", got)
	}
}
