// Package work reads and moves work items kept as files in .workline/work/,
// for projects without a forge (docs/spec/routing.md, "Work starts from a
// clear need").
package work

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/JN0V/workline/internal/forge"
	"github.com/JN0V/workline/internal/verdict"
)

// Required are the sections an item needs before it is ready.
var Required = []string{"Need", "Verification", "Validation", "Scope"}

// Path is where item id lives.
func Path(repo, id string) string {
	return filepath.Join(repo, ".workline", "work", id+".md")
}

var stateLine = regexp.MustCompile(`(?m)^state: .*$`)

// Sections returns the text under each "## " or "### " heading — an
// issue form writes its fields as the latter. A field left empty in a form
// ("_No response_") is empty.
func Sections(content string) map[string]string {
	out := map[string]string{}
	name := ""
	content, _ = Footer(content)
	for _, l := range strings.Split(content, "\n") {
		if h, ok := Heading(l); ok {
			name = h
			out[name] = ""
			continue
		}
		if name != "" {
			out[name] += l + "\n"
		}
	}
	for k, v := range out {
		if strings.TrimSpace(v) == NoResponse {
			out[k] = ""
		}
	}
	return out
}

// Footer splits a body from its footer, which belongs to no section
// (docs/spec/backlog-acts.md, "A body's footer"): from a thematic break
// (`---`, `***`, `___`, a blank line above it) after the last heading, or
// else the body's last line when it is a tool's signature alone in its
// paragraph ("🤖 Generated with …", "Generated by …"). It returns the body
// without it, its trailing blank lines too, and the footer, "" when there
// is none.
func Footer(body string) (string, string) {
	lines := strings.Split(body, "\n")
	last, fence := -1, ""
	for i, l := range lines { // the last heading, outside fenced code
		if fence = fenced(l, fence); fence != "" {
			continue
		}
		if _, ok := Heading(l); ok {
			last = i
		}
	}
	at := -1
	fence = ""
	for i, l := range lines {
		was := fence
		if fence = fenced(l, fence); fence != "" || was != "" || i <= last || last < 0 {
			continue
		}
		if thematicBreak.MatchString(strings.TrimRight(l, "\r")) && strings.TrimSpace(lines[i-1]) == "" {
			at = i
			break
		}
	}
	if at < 0 && fence == "" {
		end := len(lines) - 1
		for end >= 0 && strings.TrimSpace(lines[end]) == "" {
			end--
		}
		if end > last+1 && strings.TrimSpace(lines[end-1]) == "" && signature.MatchString(strings.TrimSpace(lines[end])) {
			at = end
		}
	}
	if at < 0 {
		return body, ""
	}
	main := strings.TrimRight(strings.Join(lines[:at], "\n"), " \r\n")
	return main, strings.Join(lines[at:], "\n")
}

// WithFooter is a body rewritten without its footer, the footer put back
// after it: a section added goes above it.
func WithFooter(main, footer string) string {
	if footer == "" {
		return main
	}
	return strings.TrimRight(main, " \r\n") + "\n\n" + footer
}

var (
	// thematicBreak is CommonMark's: three or more `-`, `*` or `_`, spaces
	// between, up to three before.
	thematicBreak = regexp.MustCompile(`^ {0,3}(?:(?:-[ \t]*){3,}|(?:\*[ \t]*){3,}|(?:_[ \t]*){3,})$`)
	// signature is the line a tool appends to what it wrote: "Generated
	// with" or "by", after an emoji or a mark.
	signature = regexp.MustCompile(`(?i)^\W*generated (?:with|by)\s+\S`)
)

// fenced is the fence open after line l, given the one open before it:
// "" outside fenced code.
func fenced(l, open string) string {
	t := strings.TrimSpace(l)
	for _, f := range []string{"```", "~~~"} {
		if strings.HasPrefix(t, f) {
			switch {
			case open == "":
				return f
			case strings.HasPrefix(open, f[:1]):
				return ""
			}
		}
	}
	return open
}

// NoResponse is what an issue form writes for a field left empty.
const NoResponse = "_No response_"

// Heading reads a section's heading line, "## Name" or "### Name".
func Heading(line string) (string, bool) {
	line = strings.TrimRight(line, "\r")
	for _, p := range []string{"## ", "### "} {
		if h, ok := strings.CutPrefix(line, p); ok {
			return strings.TrimSpace(h), true
		}
	}
	return "", false
}

// Ready moves an item to ready if its four sections are written, and says
// which are missing otherwise. It checks presence, not quality: that is the
// person's call.
func Ready(repo, id string) *verdict.Verdict {
	path := Path(repo, id)
	data, err := os.ReadFile(path)
	if err != nil {
		return &verdict.Verdict{Status: verdict.Block, Summary: "no such work item",
			Findings: []verdict.Finding{{Rule: "no-item", Where: id, Message: err.Error()}}}
	}
	if missing := check(string(data)); len(missing) > 0 {
		return &verdict.Verdict{Status: verdict.Block, Summary: "the item stays in to-refine", Findings: missing}
	}
	content := string(data)
	if stateLine.MatchString(content) {
		content = stateLine.ReplaceAllString(content, "state: ready")
	} else {
		content = "state: ready\n" + content
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return &verdict.Verdict{Status: verdict.Block, Findings: []verdict.Finding{{Rule: "engine-error", Message: err.Error()}}}
	}
	return &verdict.Verdict{Status: verdict.Pass, Summary: "item " + id + " is ready"}
}

// ReadyOnForge is Ready for an issue on a forge: the sections are read from its
// description, and a ready issue gets the workline:ready label.
func ReadyOnForge(f forge.Forge, id int) *verdict.Verdict {
	is, err := f.Issue(id)
	if err != nil {
		status := verdict.Block
		if errors.Is(err, forge.ErrUnreachable) {
			status = verdict.BlockedExternal
		}
		return &verdict.Verdict{Status: status, Findings: []verdict.Finding{{Rule: "no-item", Where: fmt.Sprint(id), Message: err.Error()}}}
	}
	if missing := check(is.Body); len(missing) > 0 {
		return &verdict.Verdict{Status: verdict.Block, Summary: "the item stays in to-refine", Findings: missing}
	}
	if err := f.Label(forge.Target{Kind: "issue", ID: id}, []string{"workline:ready"}, []string{"workline:to-refine"}); err != nil {
		return &verdict.Verdict{Status: verdict.BlockedExternal, Findings: []verdict.Finding{{Rule: "forge-unreachable", Message: err.Error()}}}
	}
	return &verdict.Verdict{Status: verdict.Pass, Summary: fmt.Sprintf("issue #%d is ready", id)}
}

func check(content string) []verdict.Finding {
	sections := Sections(content)
	var missing []verdict.Finding
	for _, r := range Required {
		if strings.TrimSpace(sections[r]) == "" {
			missing = append(missing, verdict.Finding{Rule: "not-ready", Where: r,
				Message: fmt.Sprintf("## %s is missing or empty", r)})
		}
	}
	return missing
}
